export interface ChatMessage {
  id?: string; // Optional: will be generated by the backend
  senderId: string;
  receiverId: string;
  content: string;
  timestamp: Date;
}

export interface SendMessageDto {
  senderId: string;
  receiverId: string;
  content: string;
}
